from datetime import datetime
from collections import defaultdict


LOG_FILE = "sample.log" # Name of the log file that the program will analyse
FAILED_THRESHOLD = 3 # Number of failed logins required before an IP is flagged
BLACKLISTED_IPS = {"10.0.0.5"} # IP addresses that should always be considered suspicious
WINDOW_SECONDS = 60 # Time window used to detect rapid brute-force attacks

# Store the timestamps of failed login attempts for each IP
failed_attempts = defaultdict(list)

# Store the different usernames used by each IP
# A set prevents the same username being counted multiple times
users_per_ip = defaultdict(set)

# Store all alerts generated by the detector
suspicious_events = []

# Open the log file in read mode
with open(LOG_FILE, "r") as file:
    # Process the log file one line at a time
    for line in file:
        # Remove whitespace and the newline character
        line = line.strip()
        # Split the log line into separate parts
        parts = line.split()
        # Extract and convert the timestamp
        timestamp = datetime.fromisoformat(parts[0])
        # Extract the type of event
        event_type = parts[1]
        # Extract the username
        # Example: user=alice -> alice
        user = parts[2].split("=")[1]
        # Extract the IP address
        # Example: ip=192.168.1.10 -> 192.168.1.10
        ip = parts[3].split("=")[1]


        # Track usernames used by each IP
        users_per_ip[ip].add(user) # Add the username to the set belonging to this IP

        # Detect failed login attempts
        if event_type == "FAILED_LOGIN":
            failed_attempts[ip].append(timestamp) # Store the time of the failed login for this IP
            # Check whether the IP has reached the failed-login threshold
            if len(failed_attempts[ip]) >= FAILED_THRESHOLD:
                suspicious_events.append(
                    f"[ALERT] Possible brute-force attack from {ip} "
                    f"({len(failed_attempts[ip])} failed attempts)"
                )

            # Detect rapid brute-force attacks
            attempts = failed_attempts[ip] # Get all failed attempts recorded for this IP
            # Keep only attempts that happened within the time window
            recent = [
                t for t in attempts
                if (timestamp - t).total_seconds() <= WINDOW_SECONDS
            ]

            # Flag the IP if it has made at least 5 failures within the last 60 seconds
            if len(recent) >= 5:
                suspicious_events.append(
                    f"[ALERT] Rapid brute-force attack from {ip} "
                    f"(5 failures in {WINDOW_SECONDS}s)"
                )

        # Detect successful login after repeated failures
        if (
            event_type == "SUCCESS_LOGIN"
            and len(failed_attempts[ip]) >= FAILED_THRESHOLD
        ):
            suspicious_events.append(
                f"[ALERT] Successful login after repeated "
                f"failures from {ip}"
            )

        # Detect blacklisted IP addresses
        if ip in BLACKLISTED_IPS:
            suspicious_events.append(
                f"[ALERT] Connection from blacklisted IP: {ip}"
            )


# Detect multiple usernames being attempted from the same IP
# Check each IP and the usernames associated with it
for ip, users in users_per_ip.items():
    # Flag an IP if it has attempted to use at least 3 usernames
    if len(users) >= 3:
        suspicious_events.append(
            f"[ALERT] Multiple usernames attempted from {ip}: "
            f"{', '.join(users)}"
        )

# Display the threat detection report
print("=== Threat Detection Report ===")
# Print every alert that was generated
for event in suspicious_events:
    print(event)

# Save the alerts to a text report
# Open/create the report file - "w" to overwrite the old report so its replaced each time the program runs
with open("reports/threat_report.txt", "w") as report:

    # Write every alert into the report
    for event in suspicious_events:
        report.write(event + "\n")